#version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: docnest-postgres
    environment:
      POSTGRES_DB: docnestdb
      POSTGRES_USER: docnest
      POSTGRES_PASSWORD: docnestpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 